#!/bin/sh
#=======================================================================
#	Fix up filetree exported from docker
#=======================================================================
target=$1

fakeetc=/var/local

# Docker envoronment
rm -f "$target/.dockerenv"

# Some files are overridden by docker, so put elsewhere by the build scripts
for file in hostname hosts resolv.conf mtab; do
    if [ -e "$target$fakeetc/$file" -o -L "$target$fakeetc/$file" ]; then
	rm -f "$target/etc/$file"
	mv "$target$fakeetc/$file" "$target/etc/$file"
    fi
done
# Remove fake /etc unless it has re-used e.g. /var/local
case "$fakeetc" in
    /fakeetc)
	rm -fr "$target$fakeetc"
	;;
esac

# Remove proxy setting used at build time
rm -f "$target/etc/apt/apt.conf.d/51-iisysgen-proxy.conf"
rm -f "$target/etc/apt/apt.conf.d/51cache"

# Helper files from iisysgen
rm -fr "$target/helpers"

# qemu for foreign architecture
rm -f "$target/usr/bin/qemu-arm-static"

# .deb files (equivalent to apt-get clean)
find "$target/var/cache/apt/archives" -type f \( -name lock -o -print0 \) |
    xargs -0 rm -f

# Files updated during build but not needed
rm -f \
   "$target/etc/apt/sources.list~" \
   "$target/etc/apt/trusted.gpg~" \
   "$target/etc/passwd-" \
   "$target/etc/group-" \
   "$target/etc/shadow-" \
   "$target/etc/gshadow-" \
   "$target/etc/subuid-" \
   "$target/etc/subgid-" \
   "$target/var/cache/debconf/"*-old \
   "$target/var/lib/dpkg/"*-old \
   "$target/var/lib/apt/lists/"*_*

# Packages from same source package typically share changelog.gz
if [ -x /usr/bin/hardink ]; then
    hardlink -t /target/usr/share/doc
fi
